name: Feature request
description: Suggest a new idea for Kelivo.
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Kelivo!
        
        Before filling the form fields, please consider the following:
        - Ensure that you have searched the [existing issues](https://github.com/Chevey339/kelivo/issues)
        - Check if there's already a similar feature request or discussion
  - type: textarea
    attributes:
      label: Motivation
      description: |
        应该建立或改进什么功能？完成后目标用户的生活会有什么改善？
        
        What capability should be either established or improved? 
        How is life of the target audience better after it's been done?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: |
        如果你已经有了实现想法，请在此描述。  
        
        If you already have an idea how this can be implemented, please describe it here.
        This allows potential other contributors to join forces and provide meaningful 
        feedback prior to even starting work on it.
        
        Consider attaching something showing what you are imagining:
         * images
         * videos
         * code samples
         * mockups or wireframes
    validations:
      required: false